### ISSUE TITLE
Decide whether FDX should continue as Program or multiple Projects

### ISSUE THREAD

**Issue by mindthegab** [finos/fdx-pmc#2]
FDX PMC, 

As you should know by now [as previously communicated](https://groups.google.com/a/finos.org/forum/#!topic/pmcs/e7dpjwbC9q8), the Board has approved the deprecation of the construct of Programs as a governance Body. The plan was outlined in the [Program Deprecation RFC](https://github.com/finos/finos-pmcs/pull/22#issuecomment-617451699).

In short, Programs have the option to reduce governance overhead continuing as one / more  independent Projects or to continue working with the current Governance as a Program. 

If you have any questions please let's collaborate on this issue but if you are ready to vote already please feel free to do so, by adding a comment to this issue with one of the two options:

- 👍 (to disband the Program and continue as multiple top level Projects hosted under the main FINOS github org) 

or

- 👎 (to continue operating as the FDX Program)

To see how other Programs are doing it (either via email list, or github issue or a meeting), we are tracking the process and results for all Programs [in this issue](https://github.com/finos/finos-pmcs/issues/31).

Thanks for your contribution and leadership to grow our Foundation so far, we look forward to an even faster growth for our Projects moving forward - accelerating the (OSS) financial developer experience is more important than ever!

**Comment by mindthegab** [comment]
@jbjonesjr @ColinEberhardt @copiesofcopies @bingenito @davidwatkins73 @git-hub-forwork1 can you cast your votes at your earliest convenience?

@maoo (thanks for voting already)

**Comment by bingenito** [comment]
@mindthegab Done

**Comment by copiesofcopies** [comment]
👍 Open Source Readiness is prepared to go it alone.

**Comment by git-hub-forwork1** [comment]
Cloud service certification can go on it's own.  Not strong in that opinion but seems possible.

**Comment by jbjonesjr** [comment]
Way too early of a question: Do we see a near future including Special Interest Groups like in CNCF? https://github.com/cncf/toc

Many of the FDX projects are not traditional code-based projects or tools, and am curious if some other structure (or a continued light-weight program/pmc) might make the most sense.

**Comment by mindthegab** [comment]
In my personal opinion and in principle, +100.

The flip side is that I would explore support and commitment for the TAC
and then have the TAC initiate top down or approve bottom up SIGs with some
specific charter directly connected to key areas/business challenges
important to the Board/industry.

Also to consider that the DevOps mutualization  initiative which is now a
focus project for Q2 could very well lend itself to be a SIG on an ongoing
basis.

Finally to note that some projects will be continuing with a series of
working groups (or project meetings) like FDC3. I realize thought that’s
more of 1:N use case vs. SIGs that typically are N:1.

Back to you folks :)

**Comment by ColinEberhardt** [comment]
The [cla-bot](https://github.com/finos/cla-bot) is still actively developed (and now quite widely used), I'm more than happy for this project to be run independent of an over-arching program.

**Comment by mindthegab** [comment]
@jbjonesjr Your vote is the last missing one and as PMC Lead kind of an important one :)

I can see the value of a FDX-like SIG as mentioned above, but I wonder if for now we do away with the governance overhead of the PMC (which wasn't already meeting for a while) and then explore.

Thoughts or 👍 / 👎 ? :)

**Comment by jbjonesjr** [comment]
So i'm fine doing away with the PMC if we need to make a short-term, fast change. I just don't know if all of the FDX projects (OSR, does TODO group make it redundant?, FDX, maybe even ODP) align with how the LF tends to think of `projects`. When we bring the LF community onboard, we want it to be both familiar and logical. If they start to see a bunch of `projects` that don't align with their traditional view of projects, will that cause more problems? My thinking was the PMC remains a good abstraction in the short term as we figure out where to go.

Things like the CLA-bot, various parent poms and other code projects definitely make sense to turn projects. My only concern is with the rest. maybe not.

So continuing to talk out loud:
- I have no interest in continuing the PMC, but am also unsure if everything is ready to be a separate project. Maybe we divorce these questions, which allows us to move forward now?

**Comment by mindthegab** [comment]
@jbjonesjr as usual you raise very valid points. So let's get specific and see if I can put forward a proposal that addresses these valid concerns. Looking at [the non-archived Projects currently in FDX](https://finos.github.io/?programShortName=FDX&state=ACTIVE&state=INCUBATING&sort=hotness-down) we currently have:

1. Waltz
2. ODP
3. Open Source License Compliance Handbook
4. cla-bot
5. Cloud Service Certification
6. Reference FOSS Policy
7. Open Source Readiness Project

So how about the following proposal:

- Disband the PMC as a governance entity / aggregation 
- In our new taxonomy/landscape, tag #3 (Open Source Compliance Handbook),  #6 (Reference FOSS Policy) and #7 (Open Source Readiness) as "open source readiness" related projects. #7 will act, as it does already, as a venue to discuss ongoing OSR related focus including how we work with TODO, OpenChain, etc (@copiesofcopies is already looking at that)
- In our new taxonomy/landscape, tag #2 (Open Developer Platform) and #4 (cla-bot) as "open source toolchain". #2 will act, as it does already, as a venue to discuss ongoing OSR related focus 
- #1 (Waltz) and #5 (cloud service certification) continue as naturally independent project and we can tag / discover them as we go (e.g. with "compliance-as-code" or "devops")
- This week we will come up with a strategy / next steps for the "DevOps mutualization" which is a Q2 focus. This might well end up needing it's own SIG or could top up on the existing ODP venue, depending on the scope that's decided.

I feel like this proposal addresses your concerns of having a more "high level" venue for initiatives like ODP and OSR (the real discussion groups here) while allowing for the governance to be streamlined (I'm not sure when the last time this PMC met is).

@jbjonesjr wdyt?

**Comment by mindthegab** [comment]
@jbjonesjr bumping this for your consideration. Do you agree with the proposal above? This is the last program to make a decision. No rush but it has a big impact on how we clean up our governance moving forward, so would be good to have an answer by tomorrow.

**Comment by jbjonesjr** [comment]
@mindthegab Mostly 👍.

I'd move `cla-bot` into an individual project (it can act like it always has as well, and has good code assets).

I'd then pair the ODP with the upcoming DevOps mutualization item (was their any updates on that from last week) and call them something like "Developer Toolchain" or something. 

The rest of your recommendation looked PERFECT, and captures my thoughts and concerns wonderfully.

**Comment by mindthegab** [comment]
Thanks @jbjonesjr - that's great. 

So recapping for @maoo's mostly and for the rest of the PMC @copiesofcopies @bingenito @git-hub-forwork1 @ColinEberhardt @davidwatkins73, the decision is:

1. Disband the FDX Program and discontinue PMC meetings
2. Move cla-bot, Waltz and Cloud service certification as top-level projects
3. Move OSR Project, OSLC Handbook and reference FOSS policy as top-level projects - OSR project meetings continue to be the connection point where existing and new open source readiness projects are discussed. We will reflect that in the taxonomy and @copiesofcopies maybe you want to update the OSR wiki to directly reference these related projects?
4. Move ODP to top level and, if and when DevOps mutualization comes out of formation, make sure we clarify the relationship with ODP (separate meetings or merge). ODP becomes the primary venue to discuss FINOS infrastructure and more generally financial services developer toolchain conversations (again, potentially DevOps mutualization will be its own project or set of projects). To your questions, @jbjonesjr, yes we are ready with next steps on DevOps mutualization - @mcleo-d is taking the lead and follow up in the next day or so.

I'll leave this issue open until tomorrow if there's any disagreement from the PMC, otherwise we will proceed with the changes.

Thanks for the very productive discussion!

**Comment by jbjonesjr** [comment]
:+1: thanks @mindthegab

**Comment by maoo** [comment]
All done on FINOS metadata.

@aitana16 - can you please double check the program calendar, although there should be no FDX PMC activity planned.

@jbjonesjr - are you ok to archive https://github.com/finos/fdx-pmc and use https://github.com/finos/finos-pmcs for these type of (future) conversations?

Note, `fdx-pmc` will be shortly renamed to reflect program disband, see https://github.com/finos/finos-pmcs/issues/36

**Comment by agitana** [comment]
hi @maoo I can confirm that there are no FDX PMC activities scheduled on the FINOS Programs calendar.

**Comment by mindthegab** [comment]
Perfect, closing this one then.
